<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <!-- Conditional reference for local development -->
    <ProjectReference Include="..\FireballEngine.OpenGL\FireballEngine.OpenGL.csproj" Condition="'$(Configuration)' == 'Debug'" />
    <!-- Conditional reference for NuGet package -->
    <PackageReference Include="FireballEngine.OpenGL" Version="0.1.0-alpha" Condition="'$(Configuration)' != 'Debug'" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FireballEngine.DemoGame\FireballEngine.DemoGame.csproj" />
  </ItemGroup>

  <Target Name="SyncGameAssets" AfterTargets="Build">
    <!-- Delete existing assets folder in output directory -->
    <RemoveDir Directories="assets\" Condition="Exists('$(assets\')" />

    <!-- Recreate the folder to avoid errors -->
    <MakeDir Directories="assets\" />

    <!-- Collect all assets from DemoGame -->
    <ItemGroup>
        <GameAssets Include="..\FireballEngine.DemoGame\assets\**\*" />
    </ItemGroup>

    <!-- Copy assets while preserving the directory structure -->
    <Copy SourceFiles="@(GameAssets)"
          DestinationFolder="assets\%(RecursiveDir)" />
  </Target>
</Project>
