<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <PackageId>FireballEngine.Core</PackageId>
    <Version>$(Version)</Version>
    <Authors>Clayton Hunt</Authors>
    <Description>Core library for the Fireball Engine</Description>
    <IsPackable>true</IsPackable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
